### ISSUE TITLE
Hitting Ctrl-C while running chericat -p on a target kills the target

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/chericat#32] opened 2024-03-25 07:26 UTC
When I run `chericat -p` on a target process, and then hit Ctrl-C during the scan, the target process is terminated:

```
robert@cheri-blossom:~/chericat % sleep 1000 &
[1] 5475
robert@cheri-blossom:~/chericat % bin/chericat -p 5475 -v
^C
robert@cheri-blossom:~/chericat % 
[1]    Killed                        sleep 1000
```

Ideally, `chericat` would catch `SIGINT` and allow the process to resume normally. Or, perhaps more ideally, there would be a way to use `ptrace(2)` such that this didn’t happen, but I’m not sure that’s possible if a target process is suspended.

**Comment by psjm3** [comment] 2024-06-06 19:51
This PR should help with this issue: https://github.com/CTSRD-CHERI/chericat/pull/40, which has been merged.

Please reopen this issue if the problem is still there.

**Closed by psjm3** 2024-06-06 19:51 UTC
